apiVersion: v1
data:
  bootstrap.memory_lock: "false"
  cluster.initial_master_nodes: 'es-cluster-0,es-cluster-1'
  cluster.name: 'k8s-cluster'
  discovery.seed_hosts: 'es-cluster-0.elasticsearch,es-cluster-1.elasticsearch'
  ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  REDIS_MASTER_HOST: 'redis-master'
  REDIS_SLAVE_HOST: 'redis-slave'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-config
