apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
          env:
            - name: bootstrap.memory_lock
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: bootstrap.memory_lock
            - name: cluster.initial_master_nodes
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: cluster.initial_master_nodes
            - name: cluster.name
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: cluster.name
            - name: discovery.seed_hosts
              valueFrom:
                configMapKeyRef:
                  name: es-config
                  key: discovery.seed_hosts
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9300
              name: inter-node
          resources:
            requests:
              cpu: "100m"
              memory: "512M"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
